# This rule is not used by the project key-encryption-granter itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sijoma.sijoma.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: key-encryption-granter
    app.kubernetes.io/managed-by: kustomize
  name: encryptionkey-admin-role
rules:
- apiGroups:
  - sijoma.sijoma.io
  resources:
  - encryptionkeys
  verbs:
  - '*'
- apiGroups:
  - sijoma.sijoma.io
  resources:
  - encryptionkeys/status
  verbs:
  - get
