---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - sijoma.sijoma.io
  resources:
  - encryptionkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sijoma.sijoma.io
  resources:
  - encryptionkeys/finalizers
  verbs:
  - update
- apiGroups:
  - sijoma.sijoma.io
  resources:
  - encryptionkeys/status
  verbs:
  - get
  - patch
  - update
